// Compatibility layer for legacy imports. Do not add new implementations here.
export * from './shared.types'
export * from './overview.api'
export * from '../user/api'
export * from '../bed/api'
export * from '../check-in/api'
export * from '../check-out/api'
export * from '../meal/api'
export * from '../meal-calendar/api'
export * from '../outing/api'
export * from '../service-target/api'
export * from '../service-focus/api'
