export const CARE_PATTERNS = {
  dashboardSummary: { cmd: 'care.dashboard.summary' },
  customerModules: { cmd: 'care.customer.modules' },
  customerOverview: { cmd: 'care.customer.overview' },
  residentsList: { cmd: 'care.customer.residents.list' },
  residentsCreate: { cmd: 'care.customer.residents.create' },
  residentsUpdate: { cmd: 'care.customer.residents.update' },
  usersList: { cmd: 'care.customer.users.list' },
  usersCreate: { cmd: 'care.customer.users.create' },
  usersUpdate: { cmd: 'care.customer.users.update' },
  roomsList: { cmd: 'care.customer.rooms.list' },
  roomsCreate: { cmd: 'care.customer.rooms.create' },
  roomsUpdate: { cmd: 'care.customer.rooms.update' },
  bedsList: { cmd: 'care.customer.beds.list' },
  bedsCreate: { cmd: 'care.customer.beds.create' },
  bedsUpdate: { cmd: 'care.customer.beds.update' },
  mealPlansList: { cmd: 'care.customer.meal-plans.list' },
  mealPlansCreate: { cmd: 'care.customer.meal-plans.create' },
  mealPlansUpdate: { cmd: 'care.customer.meal-plans.update' },
  mealCalendarsList: { cmd: 'care.customer.meal-calendars.list' },
  mealCalendarsCreate: { cmd: 'care.customer.meal-calendars.create' },
  mealCalendarsUpdate: { cmd: 'care.customer.meal-calendars.update' },
  checkInsList: { cmd: 'care.customer.check-ins.list' },
  checkInsCreate: { cmd: 'care.customer.check-ins.create' },
  checkOutsList: { cmd: 'care.customer.check-outs.list' },
  checkOutsCreate: { cmd: 'care.customer.check-outs.create' },
  outingsList: { cmd: 'care.customer.outings.list' },
  outingsCreate: { cmd: 'care.customer.outings.create' },
  outingsReturn: { cmd: 'care.customer.outings.return' },
  serviceTargetsList: { cmd: 'care.customer.service-targets.list' },
  serviceTargetsCreate: { cmd: 'care.customer.service-targets.create' },
  serviceTargetsUpdate: { cmd: 'care.customer.service-targets.update' },
  serviceFocusesList: { cmd: 'care.customer.service-focuses.list' },
  serviceFocusesCreate: { cmd: 'care.customer.service-focuses.create' },
  serviceFocusesUpdate: { cmd: 'care.customer.service-focuses.update' },
  nursingModules: { cmd: 'care.nursing.modules' },
  careLevelsList: { cmd: 'care.nursing.levels.list' },
  careLevelsCreate: { cmd: 'care.nursing.levels.create' },
  careLevelsUpdate: { cmd: 'care.nursing.levels.update' },
  careItemsList: { cmd: 'care.nursing.items.list' },
  careItemsCreate: { cmd: 'care.nursing.items.create' },
  careItemsUpdate: { cmd: 'care.nursing.items.update' },
  careRecordsList: { cmd: 'care.nursing.records.list' },
  careRecordsCreate: { cmd: 'care.nursing.records.create' },
  careRecordsUpdate: { cmd: 'care.nursing.records.update' },
} as const

export type UpdateWithId<T> = {
  id: number
  data: T
}
